export const sample_data = [
    {
        id: '1',
        name: 'Batman One Dark Knight',
        price: '12.59',
        creators: ['Jock', 'Clem Robins', 'Bob Kane', 'Bill Finger'],
        releaseYear: '2022',
        studio: 'DC',
        imageUrl: 'comic_1.jpg',
    },
    {
        id: '2',
        name: 'Batman: Arkham Asylum',
        price: '26.59',
        creators: ['Grant Morrison', 'Dave McKean'],
        releaseYear: '2021',
        studio: 'DC',
        imageUrl: 'comic_2.jpg',
    },
    {
        id: '3',
        name: 'Darth Vader #1',
        price: '15.59',
        creators: ['Charles Soule', 'Giuseppe Camuncoli'],
        releaseYear: '2017',
        studio: 'Marvel',
        imageUrl: 'comic_3.jpg',
    },
    {
        id: '4',
        name: 'Deadpool: Worlds Greatest #1',
        price: '10.20',
        creators: ['Gerry Duggan', 'Mike Hawthorne', 'Tony Moore'],
        releaseYear: '2016',
        studio: 'Marvel',
        imageUrl: 'comic_4.jpg',
    },
    {
        id: '5',
        name: 'Daredevil: Born Again',
        price: '16.59',
        creators: [' Frank Miller', 'David Mazzucchelli'],
        releaseYear: '2010',
        studio: 'Marvel',
        imageUrl: 'comic_5.jpg',
    },
];